# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/hardware/network/broadcom-43xx.nix")
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/051561d1-c97d-4318-a6a5-3680888485cc";
      fsType = "btrfs";
      options = [
        "subvol=root"
        "compress=zstd"
        "x-initrd.mount"
        "discard=async"
        "noatime"
        "commit=120"
      ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/051561d1-c97d-4318-a6a5-3680888485cc";
      fsType = "btrfs";
      options = [
        "subvol=home"
        "compress=zstd"
        "discard=async"
        "noatime"
      ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/051561d1-c97d-4318-a6a5-3680888485cc";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "noatime"
        "compress=zstd"
        "x-initrd.mount"
        "discard=async"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7B84-3313";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/dbded80d-0887-4c30-a025-a0d847038af5";
        options = [ "discard" ];}
    ];

  networking.useDHCP = lib.mkDefault true;

  #   nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
