# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cdce2bcf-bfa9-4862-bba7-b374bf908624";
      fsType = "btrfs";
      options = [
        "subvol=root"
        "compress=zstd"
        "x-initrd.mount"
        "discard=async"
        "noatime"
        "commit=120"
      ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/cdce2bcf-bfa9-4862-bba7-b374bf908624";
      fsType = "btrfs";
      options = [
        "subvol=home"
        "compress=zstd"
        "discard=async"
        "noatime"
      ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/cdce2bcf-bfa9-4862-bba7-b374bf908624";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "noatime"
        "compress=zstd"
        "x-initrd.mount"
        "discard=async"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/423E-B438";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/22cd47e7-e1ae-42e3-8de1-48c10d068544";
      options = [ "discard" ];
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
