# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6d1d0a39-eaf7-4d9b-a6a6-45fa0a7b7361";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6d1d0a39-eaf7-4d9b-a6a6-45fa0a7b7361";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/6d1d0a39-eaf7-4d9b-a6a6-45fa0a7b7361";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/6d1d0a39-eaf7-4d9b-a6a6-45fa0a7b7361";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/6d1d0a39-eaf7-4d9b-a6a6-45fa0a7b7361";
      fsType = "btrfs";
      options = [ "subvol=@srv" "compress=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/6d1d0a39-eaf7-4d9b-a6a6-45fa0a7b7361";
      fsType = "btrfs";
      options = [ "subvol=@cache" "noatime" "discard=async" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/6d1d0a39-eaf7-4d9b-a6a6-45fa0a7b7361";
      fsType = "btrfs";
      options = [ "subvol=@log" "noatime" "discard=async" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/6d1d0a39-eaf7-4d9b-a6a6-45fa0a7b7361";
      fsType = "btrfs";
      options = [ "subvol=@tmp" "noatime" "discard=async" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/359C-4B64";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
